name: CI Workflow
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo and Submodules
        uses: actions/checkout@v2
        with:
          submodules: 'true'
        
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.10
          
      - name: Install Go Deps
        run: go mod download

      - name: Build
        run: go build -v ./...
        
      - name: Test
        run: go test -v $(go list ./... | grep -v /vendor/)
